log_format json_log escape=json
    '{'
    '"time":"$time_iso8601",'
    '"status":$status,'
    '"method":"$request_method",'
    '"uri":"$request_uri",'
    '"body_bytes_sent":$body_bytes_sent,'
    '"request_time":$request_time,'
    '"remote_addr":"$remote_addr",'
    '"user_agent":"$http_user_agent",'
    '"referer":"$http_referer"'
    '}';

access_log /dev/stdout json_log;

server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }
}
